### ISSUE TITLE
java.lang.IllegalStateException: Content View height is too small

### ISSUE THREAD

**Issue by HarshSanghvi** [Ramotion/folding-cell-android#11]
at com.ramotion.foldingcell.FoldingCell.calculateHeightsForAnimationParts(FoldingCell.java:257)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at com.ramotion.foldingcell.FoldingCell.unfold(FoldingCell.java:118)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at com.ramotion.foldingcell.FoldingCell.toggle(FoldingCell.java:206)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at com.broadamptechnologies.bricks.NewsFragment$2.onClick(NewsFragment.java:97)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.view.View.performClick(View.java:5198)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-22 13:21:00.109 6283-6283/com.broadamptechnologies.bricks W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
04-22 13:21:00.110 6283-6283/com.broadamptechnologies.bricks W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-22 13:21:00.110 6283-6283/com.broadamptechnologies.bricks W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-22 13:21:00.110 6283-6283/com.broadamptechnologies.bricks W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by oleg-vasiliev** [comment]
As you can see in the exception message - "Content View height is too small". Content view height must be at least twice bigger than title view

**Comment by pecabum** [comment]
well... my view is 4 times bigger . still geting the same issue

**Comment by MostafaEbrahimi** [comment]
I have same issue . and change content 2 times bigger than title but have same exception

**Comment by MostafaEbrahimi** [comment]
I think you need to  change `LinearLayout` in sample code in `cell_content_layout.xml/cell_list_view_example` and `cell_title_layout.xml/cell_list_view_example` to  `FrameLayout`

**Comment by Abdohurbly** [comment]
The Same goes here ....

**Comment by LambdaDigamma** [comment]
Same here

**Comment by noamamiran** [comment]
Same here, for me it happens in rare cases...
My crash cause when i call fold animation during oncreate with some kind of delay, but I guess I need to listen to ViewTreeObserver.onGlobalLayout

**Comment by aliSalah96** [comment]
Same here , sol plz

**Comment by emailsubjekt** [comment]
I get when I open one , the 3rd or 4th also opens beyond the scope of the screen, also the 10th and the 15th, so you have 4 open when you opened only one, then you have to close all 4
