### ISSUE TITLE
draw problem when quick expand from bottom to top in recyclerview

### ISSUE THREAD

**Issue by Gredus** [Ramotion/folding-cell-android#12]
![screenshot_2016-05-01-17-07-25](https://cloud.githubusercontent.com/assets/18277946/14941064/6e62ad6e-0fc1-11e6-9e76-8b74f28065d2.png)
![screenshot_2016-05-01-17-07-13](https://cloud.githubusercontent.com/assets/18277946/14941065/6ea9b81c-0fc1-11e6-941b-c997f37664c2.png)

**Comment by uditunpluged** [comment]
I am also facing the same problem ! Did you find any fix for this.

**Comment by olsynt** [comment]
Disable animation in `onBindView`

You can use : https://github.com/Ramotion/folding-cell-android/issues/16

**Comment by uditunpluged** [comment]
I am using ListView and facing the same issue

**Comment by msaada** [comment]
Any news on how to fix this problem ?

**Comment by Juriv** [comment]
guys, could you please explain what's the issue, it's not clear from the screenshots

**Comment by cazador4** [comment]
Same error here. Please see the gif below:

![foldingcellerror](https://user-images.githubusercontent.com/867465/27547462-7a33f87c-5a6c-11e7-9875-2a29e84543b9.gif)

**Comment by kevin4dhd** [comment]
+1

**Comment by golovin47** [comment]
Hello, guys. This issue was resolved in new version. Please update to the new version of this lib. It is also now migrated to androidX.
