### ISSUE TITLE
Use recyclerview foldingcell, will appear this problem, how should I solve?

### ISSUE THREAD

**Issue by zzhhz** [Ramotion/folding-cell-android#13]
When an open item, sliding half way to hide this item, click this item, there will be a foldingcell cannot fold, click again, although there is a click event, but no effect, how should this change
<img width="478" alt="123" src="https://cloud.githubusercontent.com/assets/12537706/15142671/b151aed6-16d8-11e6-967f-533717377c65.png"><br/>
<img width="478" alt="124" src="https://cloud.githubusercontent.com/assets/12537706/15142685/c3865ebc-16d8-11e6-9ab7-bfb1c02a8e7a.png"><br/>
<img width="476" alt="125" src="https://cloud.githubusercontent.com/assets/12537706/15142700/d33bac04-16d8-11e6-8c5c-c2bace8169b2.png">

**Comment by oleg-vasiliev** [comment]
Unfortunately I can't reproduce this behavior using any of provided examples from repository. Can you provide more details about your layout and code?

**Comment by zzhhz** [comment]
I see lastest version, already fixing bugs, thanks!

**Comment by EricMartori** [comment]
I have this very same issue. Is there a new released version that fixes it? I'm using CardView as the root elements of the folded and unfolded cells if it matters.
