### ISSUE TITLE
can't upload application to Google Play store

### ISSUE THREAD

**Issue by MaxToyberman** [Ramotion/folding-cell-android#14]
I have tried to publish my application to Google Play store but when i include the 
'com.ramotion.foldingcell:folding-cell:1.0.0'  I get the following error when trying to upload
apk file. 
the dependency causes the next Issue:
Multiple APK: Version 1 is not served to any device configuration.

**Comment by MaxToyberman** [comment]
after a little research i found out here in the manifest:

https://github.com/Ramotion/folding-cell-android/blob/master/folding-cell/src/main/AndroidManifest.xml

it is written
`<uses-sdk android:maxSdkVersion="17" />`

it should be
` <uses-sdk android:minSdkVersion="17" />`

beacuse as stated in your documentation it is stated Android 4.2.2 Jelly Bean (API lvl 17) or greater

**Comment by oleg-vasiliev** [comment]
thanks, fixed in 1.0.1 version.

**Comment by Mardoqueu** [comment]
What's your application name?

**Comment by MaxToyberman** [comment]
It is called Kipmi but it is still in beta testing ,We will inform you when
it is done !
Thank you for reviewing the Issue.

**Comment by Mardoqueu** [comment]
Okay! I thought it already could be available on play store. I'd like to see it for sure. Thanks for your answering

**Comment by MaxToyberman** [comment]
I will let you know when it's done !! by the way ,it looks great !
