### ISSUE TITLE
Unable to fold if there are buttons in expand cell

### ISSUE THREAD

**Issue by txadf** [Ramotion/folding-cell-android#17]
in the expand cell ,i want to add some buttons and set listener for them ,but the expand cell can`t fold,can you give me some suggestions to solve  it,thand you!

**Comment by txadf** [comment]
use the TextView replace Button can solve the problem

**Comment by VictorRamCode** [comment]
Do you have support for EditText Integration? I want add interaction on each card....

**Comment by txadf** [comment]
Sorry， I don't understand what you said. It can use EditText in the expand cell ,i ever used it

**Comment by VictorRamCode** [comment]
I want to use a sfd in the expanded cell, it is possible to integrate , but I have problems back to collapse the cell, as occurs when I add buttons. :(

**Comment by txadf** [comment]
May be the button  hava  the focus,  do you try to use the TextView replace Button .

**Comment by VikingPingvin** [comment]
I ran into this same issue? Any way to retain the Button Functionality?

**Comment by oleg-vasiliev** [comment]
I added samples of working with button click handlers to listview example project in repo.
