### ISSUE TITLE
Wrong behavior expand and collapse on recyclerview 

### ISSUE THREAD

**Issue by araurangel** [Ramotion/folding-cell-android#18]
I got problem while using recyclerview because recyclerview is recycle it make item collapse and expand in wrong position while you scroll with recyclerview have alot item... are there any idea I could solve this problem ? @Pakhaliuk

**Comment by patrickds** [comment]
Take a look at the [https://github.com/Ramotion/folding-cell-android/blob/master/folding-cell-listview-example/src/main/java/com/ramotion/foldingcell/examples/listview/FoldingCellListAdapter.java](adapter) used in the example. 
Basically everytime a cell is unfolded you save its index in a list, then when creating the view (binding in recycler view) you lookup at the list of unfolded indexes and call **cell.unfold(true)** if the current index is in that list. Note the **true** parameter indicating to skip the animation.

Hope it helps.

**Comment by oleg-vasiliev** [comment]
As noted by Patrick
