### ISSUE TITLE
Folding Cell title question

### ISSUE THREAD

**Issue by FedeDP** [Ramotion/folding-cell-android#22]
Hi!
Thanks for this lib!

How can I "unfold" my cell without hiding title? Ie: it now works this way: 
title shown, content hidden -> click -> title hidden, content shown.

How can I reach this behaviour?
title shown, content hidden -> click -> title shown, content shown.

Thanks!

**Comment by oleg-vasiliev** [comment]
The behavior that you describe breaks a physical sense of revealing card content - title of card hiding on the opposite side when card is open.
But you can duplicate your card title in top part of your card content. :)
