### ISSUE TITLE
Weird folding animation

### ISSUE THREAD

**Issue by Molteh** [Ramotion/folding-cell-android#26]
I'm currently using the folding cell examples + one with a layout of my own, no behavior problems but in all the projects, including the example you provide, while expanding or collapsing the cell edges tent to cover a good portion of the screen in a completely unnatural way. I'm using normal Listviews and android 6.0 on a Nexus 5.
I attached a link to a screenshot to make the problem clear, in my opinion, while folding, the cell should never overlap with other listview elements, this 3D effect almost give the sensation that the user is being hit. I'd like to know if there is something that could be done to solve this issue

Screenshot link:
https://www.dropbox.com/s/2wdfcxc06k5log8/Screenshot_20160916-153314.png?dl=0

**Comment by oleg-vasiliev** [comment]
In next version I will add additional parameter for change level of this 3d effect. So will be possible to control overlapping between elements by changing level of 3d effect and free spaces between elements.

**Comment by oleg-vasiliev** [comment]
fixed in 1.1.0
