### ISSUE TITLE
Question: Start with cells unfolded

### ISSUE THREAD

**Issue by el-samiyel** [Ramotion/folding-cell-android#27]
Hi, brilliant work first of all!

Question, is it possible to start with the cells unfolded?

I cant seem to find any documentation on the matter..

Many Thanks

**Comment by oleg-vasiliev** [comment]
Unfortunately, in this version there is no such possibility. Perhaps I will implement this feature in the next version. Also you can try to implement this by yourself and create a pull request, I'm sure that this is not difficult.

**Comment by kvaruna** [comment]
Is this done yet?
