### ISSUE TITLE
Unable to collapse the cell when listview is added to the content layout

### ISSUE THREAD

**Issue by nidhinkumar06** [Ramotion/folding-cell-android#28]
I have used a listview inside the content layout it gets expanded nicely but it is not  getting collapsed so what would i do in it

**Comment by oleg-vasiliev** [comment]
Unfortunately I can not help you because you did not provide the source code, or at least part of the source code that shows how you use Folding Cell. Make sure that you have correctly implemented all callbacks for fold/unfold. Also you can examine some examples in the repository.

**Comment by nidhinkumar06** [comment]
Thanks for the reply Oleg but I would like to know if we use a list inside
the content layout will it work because previously I have used button which
didn't collapse the cell that's why I have asked any way I will post the
code also.

On Oct 11, 2016 12:45 PM, "Oleg Vasiliev" <notifications@github.com> wrote:

Unfortunately I can not help you because you did not provide the source
code, or at least part of the source code that shows how you use Folding
Cell. Make sure that you have correctly implemented all callbacks for
fold/unfold. Also you can examine some examples in the repository.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ramotion/folding-cell-android/issues/28#issuecomment-252831969>,
or mute the thread

**Comment by ccparram** [comment]
I have the same issue. Basically, when you add a RecyclerView to content layout, you can't collapse the cell. Adding a ListView you can collapse the cell, only if you don't fill the ListView. After fill the ListView, it's impossible collapse the cell.
