### ISSUE TITLE
folding does not work, if i use switch or toggle switch

### ISSUE THREAD

**Issue by khemrajsharma** [Ramotion/folding-cell-android#33]
Dear sir,
I use your example of folding list view. If i put a switch on title view then it does not unfold at all. You are using textview as button in your code. Sir but i need to use switch or toggle. help me please.
thank you,
Khemraj
I am using title layout code as below:

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/title_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/content_layout"
        android:background="@color/bgContent"
        android:baselineAligned="false"
        android:orientation="horizontal"
        android:visibility="visible">

        
        
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:background="@color/colorPrimary"
            android:orientation="horizontal"
            android:paddingBottom="5dp"
            android:paddingLeft="5dp"
            android:paddingRight="5dp"
            android:paddingTop="5dp">

            <TextView
                android:id="@+id/name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:layout_weight="5"
                android:text="KHEMRAJ SHARMA"
                android:textColor="@android:color/white"
                android:textSize="20sp" />

            <Switch
                android:id="@+id/switch_mlatch"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_gravity="center_vertical"
                android:layout_weight="1"
                 />

        </LinearLayout>
    </LinearLayout>

**Comment by oleg-vasiliev** [comment]
![image](https://user-images.githubusercontent.com/7147660/27227759-781a5ce6-52ad-11e7-80be-e83363fd9b24.png)
![image](https://user-images.githubusercontent.com/7147660/27227774-8aaea9c0-52ad-11e7-942a-e9ad66393767.png)
