### ISSUE TITLE
Calling toggle(true) o unfold(true) makes the cell disappear

### ISSUE THREAD

**Issue by EricMartori** [Ramotion/folding-cell-android#36]
I'm having trouble with the folding cell on a recycler view. After trying to deal for hours with animation problems, and for testing purposes, I set to true the skip animation booleans to at least try to mitigate the issues I'm having (most of them already reported on other issues). Doing that I found that when I call toggle(true) or unfold(true) on a cell it disappear, but fold(true) does not.

**Comment by oleg-vasiliev** [comment]
will be fixed with #49 in version 1.2.0
