### ISSUE TITLE
folding cell in CardView with elevation and radius corner

### ISSUE THREAD

**Issue by faezesaghafi** [Ramotion/folding-cell-android#39]
Hi, I have a `RecyclerView` in my activity. I used `folding-cell` library to expand each `CardView`. but because my `CardView` has `elevation` and `cardCornerRadius` it gets ugly. because when it wants to unfold `list_item_feed_expand` first it doesn't have radius corner and shadow and when animation get completed it gets shadow and corner. it is the same for folding. it first removes radius corner and shadow and then it fold it
can you tell me how to correct this? is there anyway to solve it?

**Comment by byvlstr** [comment]
Hi, I have tried to put it into a cardView too, but it is ugly. Most of all, the flip effect is not as beautiful (flipping edges are lost in cardView width). No tweaking helped. Not even adding a rounded background scheme to the FoldingCell, as this also affected the flip animation.

It would be awesome to add cardView "support" by permitting proper elevation and rounded corners ;)

PS: Thanks for this awesome library!

**Comment by byvlstr** [comment]
I have managed to do something quite satisfying:
I have added a 'rounded corners' background to both the title view and the content view. This solved the UI problems when adding this BG to the FoldingCell itself.

My drawable:
`<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle"   >

    <solid
        android:color="#FFFFFF" >
    </solid>

    <stroke
        android:width="1dp"
        android:color="#FFFFFF" >
    </stroke>

    <padding
        android:left="5dp"
        android:top="5dp"
        android:right="5dp"
        android:bottom="5dp"    >
    </padding>

    <corners
        android:radius="4dp"   >
    </corners>

</shape>`

**Comment by s-ilnar** [comment]
Did you get a good rounding result?

**Comment by byvlstr** [comment]
> Did you get a good rounding result?

Yes, it was good!

![image](https://user-images.githubusercontent.com/13587859/68107220-6c086980-fee4-11e9-87a6-1791758fe406.png)

**Comment by s-ilnar** [comment]
I also rounded the edges using shape and corners. But for a moment, the rounding disappear when unfolding and folding. Have you been able to solve this?

<a href="http://vfl.ru/fotos/6b0f1a6028473309.html"><img src="//images.vfl.ru/ii/1573106160/6b0f1a60/28473309_m.png"  border="0"></a>

Video https://yadi.sk/i/TvU2ttTHJdzfpg

**Comment by byvlstr** [comment]
Maybe I didn't see this, because our background is white. In any case, I didn't feel having this issue and I cannot test the shown app.

**Comment by s-ilnar** [comment]
Thanks for the support!
