### ISSUE TITLE
Unfold the last two lines, the last line is not complete and cannot be folded

### ISSUE THREAD

**Issue by chenfei0928** [Ramotion/folding-cell-android#42]
In rapid succession unfold the last two lines, in the last line is not fully expanded when the penultimate line, the last line is not complete and cannot be folded
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/1905070/23885147/56a8bcce-08ac-11e7-8a8c-5276d9260a86.gif)

**Comment by woyoudianhuai** [comment]
me  too ,how to solve this

**Comment by Eun0** [comment]
me too T.T

**Comment by Waleed6886** [comment]
Any luck with this bug?

**Comment by coderaviverma** [comment]
Me Too!! Searching for solution for this issue!!!

**Comment by LokeshZade** [comment]
Use NonScrollableListView 

public class NonScrollListView extends ListView {

    public NonScrollListView(Context context) {
        super(context);
    }
    public NonScrollListView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    public NonScrollListView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }
    @Override
    public void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int heightMeasureSpec_custom = MeasureSpec.makeMeasureSpec(
                Integer.MAX_VALUE >> 2, MeasureSpec.AT_MOST);
        super.onMeasure(widthMeasureSpec, heightMeasureSpec_custom);
        ViewGroup.LayoutParams params = getLayoutParams();
        params.height = getMeasuredHeight();
    }
}



<xxxx.xxxxx.xxxxxx.xxxxx.NonScrollListView
            android:id="@+id/mainListView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#411a1919"
            android:clipChildren="false"
            android:clipToPadding="true"
            android:divider="@android:color/transparent"
            android:dividerHeight="10dp"
            android:paddingBottom="@dimen/activity_vertical_margin"
            android:paddingLeft="@dimen/activity_horizontal_margin"
            android:paddingRight="@dimen/activity_horizontal_margin"
            android:paddingTop="@dimen/activity_vertical_margin"
            android:scrollbars="none">

        </xxxx.xxxxx.xxxxxx.xxxxx.NonScrollListView>

**Comment by golovin47** [comment]
Hello, guys. This issue was resolved in new version. Please update to the new version of this lib. It is also now migrated to androidX.
