### ISSUE TITLE
How to unfold the selected cell and fold others

### ISSUE THREAD

**Issue by rmoustafa** [Ramotion/folding-cell-android#44]
Is there a way/method to unfold only the selected cell and fold the others ?

**Comment by vikaskumark** [comment]
cell is folding cell viewholder.
lastitemposition is last position clicked 

cell.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finalCell.toggle(false);
                if (unfoldedIndexes.contains(lastItemPosition)) {
                    Log.v("LastItem", "LastItem" + lastItemPosition);
                    unfoldedIndexes.remove(lastItemPosition);
                    finalCell.fold(true);
                    notifyDataSetChanged();

                }

                lastItemPosition = position;
                // register in adapter that state for selected cell is toggled
                registerToggle(position);
            }
        });

**Comment by vikaskumark** [comment]
cell.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finalCell.toggle(false);
                if (unfoldedIndexes.contains(lastItemPosition)) {
                    Log.v("LastItem", "LastItem" + lastItemPosition);
                    unfoldedIndexes.remove(lastItemPosition);
                    finalCell.fold(true);
                    notifyDataSetChanged();
                }
                lastItemPosition = position;
                // register in adapter that state for selected cell is toggled
                registerToggle(position);
            }
        });

cell is folding cell,lastItemPosition is previous clicked position

**Comment by Testator** [comment]
is registerToggle(position); the same as notifyItemChanged(position);

if not what is it?

thnx in advance
