### ISSUE TITLE
Black Stripes in folding cell while unfolding

### ISSUE THREAD

**Issue by JonasFranzDEV** [Ramotion/folding-cell-android#46]
![Uploading Screenshot_20170422-134457.png…](Example 1)
![Uploading Screenshot_20170422-134434.png…](Example 2)

Black Stripes appear when an user unfolds the cell.

**Comment by JonasFranzDEV** [comment]
![screenshot_20170422-134457](https://cloud.githubusercontent.com/assets/5757182/25304197/99050832-2762-11e7-8cfd-a136d0a1f1a2.png)
![screenshot_20170422-134434](https://cloud.githubusercontent.com/assets/5757182/25304196/990173de-2762-11e7-9b90-1caa778c4d25.png)

**Comment by KgotsoK** [comment]
Make sure that the root layout has no padding. that's what caused those lines for me previously. Example:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:folding-cell="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="8dp"
    android:clipChildren="false"
    android:clipToPadding="false"
    android:id="@+id/folding_cell_itinerary_item_holder"
    android:orientation="vertical">

    <com.ramotion.foldingcell.FoldingCell
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        folding-cell:additionalFlipsCount="2"
        folding-cell:animationDuration="800"
        folding-cell:backSideColor="@color/bgBackSideColor"
        folding-cell:cameraHeight="30"
        android:id="@+id/folding_cell_itinerary_item_dist">

        <!-- CONTENT (UNFOLDED) LAYOUT (MUST BE AT LEAST 2x times BIGGER than content layout bellow)-->
        <include layout="@layout/itinerary_itm_dist_edit_max" />


        <!-- TITLE (FOLDED) LAYOUT (MUST BE AT LEAST 2x times SMALLER than content layout above) -->
        <include layout="@layout/itinerary_itm_dist_edit_min" />


    </com.ramotion.foldingcell.FoldingCell>
</LinearLayout>
```

You can add padding/layout margins to the child layouts (The folded and the unfolded views)

**Comment by JonasFranzDEV** [comment]
@KgotsoK Thank you so much! That works for me too!

**Comment by iamadityaaz** [comment]
> @KgotsoK Thank you so much! That works for me too!

i also applied the above solution but it doesn't helped me out.
please help me with your RecyclerAdapter code.
