### ISSUE TITLE
changing cell content size 

### ISSUE THREAD

**Issue by OlegAlekos2** [Ramotion/folding-cell-android#58]
I would like to make the content layout fill the size of the screen but everytime i change size the app just crashes when i click any item in listview. 
Any Help or Suggestions ?

**Comment by mitchelldavis44** [comment]
I'm also having the same issue, is there any workaround?

**Comment by golovin47** [comment]
Hello, guys. Check again Readme of this lib, specifically Basic Usage part. Also you may check how example apps are implemented.
