### ISSUE TITLE
Adding folding cell dynamically (with PHP script)

### ISSUE THREAD

**Issue by Remilord** [Ramotion/folding-cell-android#60]
Hi,
First thanks for this awesome component. But my question is if it's possible to add to a LinearLayout some folding cell with some various content depending on my result of my request PHP script (i have already made it with some ImageView, getting data from database is not a problem).
Thanks for your consideration and sorry for my bad english i'm french.

**Comment by golovin47** [comment]
Hello, @Remilord. You can update data in your views inside FoldingCell whenever and however you want. Just get the view, which you want to update in your FoldingCell (TextView, ImageView ...) and call  the method you need.
