### ISSUE TITLE
Glitched animation when unfolded for first time

### ISSUE THREAD

**Issue by daniel-micic** [Ramotion/folding-cell-android#61]
Hi, I'm trying to solve an issue with Folding Cell element. When I unfold it for the first time, next items jump to their final position for a fraction of second and only then is their position animated according to the folding anim. It seems as if the whole layout does not have infomation about the final size of unfolded item so it needs one unfolding to compute it first. If I collapse the same item and then unfold it second time, it all works perfectly. Any idea what can I do about it ?

**Comment by moeppet** [comment]
+1

**Comment by karbyshevden** [comment]
+1

**Comment by kevin4dhd** [comment]
+1

**Comment by Ahsan221B** [comment]
+1

**Comment by golovin47** [comment]
Hello, guys. We couldn't reproduce such behavior. We updated this lib, added improvements and resolved some issues. Try to update to the most recent version of the lib.

**Comment by JasonQS** [comment]
Hi, I'm using v1.2.3 in RecyclerView or ListView, even the demo has this issue. hoping fixed, thank you!
