### ISSUE TITLE
Dynamic Height For Content_view

### ISSUE THREAD

**Issue by swapnildkapse** [Ramotion/folding-cell-android#64]
I am trying to add dynamic content in Content_View, So it can varies ex. For some there will be only 3 lines and another has 5 or you can say 6 7 lines so i want Folding cell to dynamically adjust to the height of content. Is it possible??

**Comment by golovin47** [comment]
Hello, @swapnildkapse. It is achievable. First thing you may do is reading carefully the Readme of this lib for you to know what you can do with FoldingCell. Then you can apply any logic in your list adapter.
