### ISSUE TITLE
the layout is derangement

### ISSUE THREAD

**Issue by Munccccc** [Ramotion/folding-cell-android#66]
![aa](https://user-images.githubusercontent.com/17868168/38538371-0ad2d43e-3cc6-11e8-9299-7cfb3a1bf7b2.png)

At the same time, click on two or more entries, the layout is derangement.

**Comment by Munccccc** [comment]
At present, I repair the above problems myself, your controls are really great.

**Comment by ljfyuyu** [comment]
I have the same problem.Is this problem solved?

**Comment by Munccccc** [comment]
@ljfyuyu The solution is very poor, and recyclerView is not allowed to slide during animation execution.

**Comment by ljfyuyu** [comment]
Thank you for your answer.I'll try to see it.

**Comment by sandeepkiran** [comment]
Please update the library so it works well with Recyclerview.

**Comment by golovin47** [comment]
Hello, guys. This issue was resolved in new version. Please update to the new version of this lib. It is also now migrated to androidX.
