### ISSUE TITLE
Update content view height

### ISSUE THREAD

**Issue by ykorshev** [Ramotion/folding-cell-android#69]
I want to update content view height after performing some operations (adding some text or images). But height still stays fixed.

But calling foldingCell.contentView.requestLayout() does not do anything. 

Where is the trick?

Please, help me.

**Comment by prashantkh19** [comment]
I am also facing the same problem.. did you find any solution?

**Comment by tallevi12** [comment]
@ykorshev did you find any solution?

**Comment by gsrathoreniks** [comment]
@ykorshev did you tried using
`fc.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                Toast.makeText(MainActivity.this, "Changed", Toast.LENGTH_SHORT).show();
            }
        });`

**Comment by golovin47** [comment]
Hello, guys. To apply changes to height of your list items with folding cells, you should let your list (whether it recyclerview or listview) to know that there are changes in data of your items. It may be notifyDataSetChanged() for RecyclerView for example. Also be sure that you don't use hardcoded height for your list item in layout.xml.
