### ISSUE TITLE
folding cell not working with recyclerview

### ISSUE THREAD

**Issue by abhijeetdhanawade90** [Ramotion/folding-cell-android#72]
I am using folding cell with recyclerview and when i click on any cell then this cell is not unfold.

**Comment by wifirevaithi** [comment]
did you get any answer?

**Comment by onuryurtturk** [comment]
I'm using with recyclerview and its folding. Whats your problem?

**Comment by golovin47** [comment]
Hello. You need to make a setup described in example apps and in Readme, which you can find in this repository. Also check if you set OnClickListener to your list item view and it is getting called properly. Logic of folding/unfolding should be placed in onClick() callback method.
