### ISSUE TITLE
Folding cell show grey background on fold and unfold

### ISSUE THREAD

**Issue by DiaaSaada** [Ramotion/folding-cell-android#73]
Folding cell show grey background on fold and unfold
here is a publish video of the issue
https://youtu.be/Y6rvWsaVcn8

**Comment by bermanapps** [comment]
Did you sort out this issue? I also have it!

**Comment by DiaaSaada** [comment]
We already tried that
  <com.ramotion.foldingcell.FoldingCell xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/folding_cell"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:visibility="visible"
                folding-cell:additionalFlipsCount="0"
                folding-cell:animationDuration="500"
                folding-cell:backSideColor="#FFF"
                folding-cell:cameraHeight="30">

and this

  <com.ramotion.foldingcell.FoldingCell xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/folding_cell"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:visibility="visible"
                folding-cell:additionalFlipsCount="0"
                folding-cell:animationDuration="500"
folding-cell:backSideColor="@android:color/white"
                folding-cell:cameraHeight="30">

put we still have the same issue.
please advise.

**Comment by golovin47** [comment]
Hello, @DiaaSaada. We couldn't reproduce that issue. FoldingCell takes grey color as fold/unfold background color if there is no backSideColor="@color/YOUR_COLOR" in your FoldingCell view in layout.xml. If you won't find reason of such behavior, you may fork this lib to change default background color in FoldingCell class.

**Comment by Babygalla123** [comment]
Hi.. i started working with folding cell recently.

I had created one list view with folding cell. it's working perfectly fine.
But i want to change the color of the folding cell background. As of now it's showing grey color. i had tried with backSideColor attribute also.
But still it's showing same gray color.

Please help me on this. Thanks in advance.

**Comment by golovin47** [comment]
Hi @Babygalla123. Try running example apps in this repo. Also check this lib's Readme section.
