### ISSUE TITLE
[BuggyViews] with scrolling when animation not completed

### ISSUE THREAD

**Issue by onuryurtturk** [Ramotion/folding-cell-android#76]
Hi, I'm using this library with recyclerview. Everything looks like fine but if I try to scroll down when folding animation not completed, folding cell's view is being corrupted. How can I handle this situation with refreshing the views or locking scroll state as a solution? There isn't any callback for fold animation...

**Comment by onuryurtturk** [comment]
also, it would be nice, if we have an option for single unfolded cell. Multiple unfolded cells, not creating nice aspects.

**Comment by golovin47** [comment]
Hello, @onuryurtturk. Try updating to the most recent version of folding cell lib. This issue was already resolved. If you need some additional feature, you're welcome to fork the lib and customize it the way you need.
