### ISSUE TITLE
Could not resolve com.ramotion.foldingcell:folding-cell:1.2.3.

### ISSUE THREAD

**Issue by musabeni** [Ramotion/folding-cell-android#80]
i got this error when i add this dependence on build.gradle(module:app)

**dependence** =    implementation 'com.ramotion.foldingcell:folding-cell:1.2.3'
**Error** = ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.ramotion.foldingcell:folding-cell:1.2.3.
Show Details
Affected Modules: app

**Comment by golovin47** [comment]
Hello, @musabeni. This issue isn't related to foldingcell lib. But you may check the answer here:
1. https://stackoverflow.com/questions/51218535/unable-to-resolve-dependency-for-appdebug-compileclasspath-could-not-resolv/51354236
2. https://stackoverflow.com/questions/46949622/android-studio-3-0-unable-to-resolve-dependency-for-appdexoptions-compileclas
Or in some other stackoverflow threads.
