### ISSUE TITLE
Can I use folding cell in recyclerview.

### ISSUE THREAD

**Issue by ddpatel2606** [Ramotion/folding-cell-android#81]
Hello,

You have great implementation with excellent motion.

I want to use this folding cell in recyclerView.

Is it possible?

Thanks

**Comment by golovin47** [comment]
Hello, @ddpatel2606. You can use it with recyclerview. Recyclerview basic implementation doesn't related to this lib, so you may find it in the net. Find one with DiffUtil ListAdapter, it's more convenient and effective. Then simply use FoldingCell in your recyclerview list item accordingly to readme section of this lib.
