### ISSUE TITLE
ListView not behaving well

### ISSUE THREAD

**Issue by wildstone1** [Ramotion/folding-cell-android#82]
Hi, I appreciate your work such a wonderful library
I am facing a problem if you help me out I really appreciate 

Problem:

I have a list of planets and when I click on a planet the cell unfolded and the more information is visible to the user and when the user clicks on the same view the view gets folded. but when the user scrolls down in list view and scrolls back up the same view did not get folded and it remains unfolded.

**Comment by golovin47** [comment]
Hello, @wildstone1. There is no that type of issue in sample app. I suggest you to dig deeper in the sample app and check if you have something different conceptually.
