### ISSUE TITLE
android illegal character 

### ISSUE THREAD

**Issue by hiwa-jalal** [Ramotion/folding-cell-android#85]
whenever i copy & paste code from here i get `illegal character: U+200B`

![studio64_UjjMgBV8XQ](https://user-images.githubusercontent.com/52101936/70393099-e2265180-19f7-11ea-8a4e-d9d7fcb78712.png)

**Comment by golovin47** [comment]
Hi @hiwa-jalal. There is probably somewhere an invisible character being added during copy/paste. Just write this code manually without copy/paste.
