### ISSUE TITLE
Can't load maven website!

### ISSUE THREAD

**Issue by lalrochhara** [Ramotion/folding-cell-android#94]
![IMG_20210625_161627](https://user-images.githubusercontent.com/20050789/123413748-be722e80-d5d0-11eb-9b1b-41f9be01d104.jpg)
I'm trying to download package throught site you provided but this [Maven site](http://central.maven.org/maven2/com/ramotion/foldingcell/folding-cell/1.2.3/folding-cell-1.2.3.aar) is not load anymore... it's always show like pic mentioned ☝️ ... can't load.

**Comment by olegv-ramotion** [comment]
https://mvnrepository.com/artifact/com.ramotion.foldingcell/folding-cell/1.2.3
